import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {preparedConversation,resourceArrival} from '../shared/links.mjs';
const ids=['ai-rescue','workflow-test','brand-velocity','website-enquiry'];
for(const host of ['openai','claude'])for(const id of ids)test(`${host}/${id}: one skill, scoped MCP, eight reviewer cases`,()=>{
 const p=`plugins/${host}/${id}`;const m=JSON.parse(readFileSync(p+'/.mcp.json'));assert.equal(Object.keys(m.mcpServers).length,1);assert.ok(m.mcpServers[id].url.endsWith('/mcp/'+id));assert.ok(existsSync(p+'/skills/'+id+'/SKILL.md'));assert.ok(existsSync(p+'/ui/result.html'));
 const cases=JSON.parse(readFileSync(p+'/review/cases.json'));assert.equal(cases.filter(c=>c.kind==='positive').length,5);assert.equal(cases.filter(c=>c.kind==='negative').length,3);
 const manifest=JSON.parse(readFileSync(p+(host==='openai'?'/.codex-plugin/plugin.json':'/.claude-plugin/plugin.json')));assert.equal(manifest.name,id);if(host==='openai'){assert.ok(manifest.interface.displayName.length<=30);assert.ok(manifest.interface.shortDescription.length<=30);assert.ok(manifest.interface.defaultPrompt.every(p=>p.length<=128));}
});
test('prepared conversations are distinguished from installation; URLs contain only fixed public prompts',()=>{for(const id of ids)for(const h of ['chatgpt','claude']){const r=preparedConversation(id,h);assert.equal(r.kind,'prepared-conversation');assert.ok(r.requiresHostVerification);assert.equal(new URL(r.url).searchParams.size,1);}assert.throws(()=>preparedConversation('client answers','chatgpt'));});
test('arrival attribution is public metadata only, constrained to brand resources',()=>{const u=new URL(resourceArrival('https://8gnc.io/resources/brand-velocity-check','brand-velocity','claude'));assert.equal(u.searchParams.size,4);assert.equal(u.searchParams.get('utm_source'),'claude');assert.throws(()=>resourceArrival('https://8gnc.io/?answer=secret','brand-velocity','claude'));});
test('UI uses text nodes, no answer persistence or raw-html insertion',()=>{const src=readFileSync('shared/ui/app.mjs','utf8');assert.ok(!/innerHTML|localStorage|sessionStorage|setWidgetState|fetch\(/.test(src));assert.ok(src.includes('app.downloadFile'));assert.ok(src.includes('app.updateModelContext'));});
